services:
    beyerz_api_adapter.adapter.json:
      class: Beyerz\ApiAdapterBundle\Adapter\JsonAdapter
      calls:
        - [setContainer, ['@service_container']]

    beyerz_api_adapter.adapter.xml:
      class: Beyerz\ApiAdapterBundle\Adapter\XMLAdapter
      calls:
        - [setContainer, ['@service_container']]

    beyerz_api_adapter.adapter.soap:
      class: Beyerz\ApiAdapterBundle\Adapter\SoapAdapter
      calls:
        - [setContainer, ['@service_container']]